package com.pos.controller;

import com.pos.dto.request.CompanyRequest;
import com.pos.dto.response.ApiResponse;
import com.pos.dto.response.CompanyResponse;
import com.pos.service.CompanyService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;

@RestController
@RequestMapping("/api/company")
@RequiredArgsConstructor
@Slf4j
public class CompanyController {

    private final CompanyService companyService;

    @Value("${ms.oauth.frontend-success-url:}")
    private String frontendSuccessUrl;

    @GetMapping
    public ResponseEntity<ApiResponse<CompanyResponse>> get() {
        return ResponseEntity.ok(ApiResponse.ok(companyService.get()));
    }

    @PutMapping
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<CompanyResponse>> update(
            @Valid @RequestBody CompanyRequest request,
            Authentication auth) {
        String username = auth != null ? auth.getName() : "system";
        return ResponseEntity.ok(ApiResponse.ok("Company updated", companyService.update(request, username)));
    }

    @PostMapping(value = "/logo", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<CompanyResponse>> uploadLogo(
            @RequestParam("file") MultipartFile file,
            Authentication auth) {
        String username = auth != null ? auth.getName() : "system";
        try {
            CompanyResponse updated = companyService.uploadLogo(file, username);
            return ResponseEntity.ok(ApiResponse.ok("Logo uploaded", updated));
        } catch (Exception e) {
            return ResponseEntity.badRequest()
                    .body(ApiResponse.<CompanyResponse>error("Logo upload failed: " + e.getMessage()));
        }
    }

    @PostMapping(value = "/favicon", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<CompanyResponse>> uploadFavicon(
            @RequestParam("file") MultipartFile file,
            Authentication auth) {
        String username = auth != null ? auth.getName() : "system";
        try {
            CompanyResponse updated = companyService.uploadFavicon(file, username);
            return ResponseEntity.ok(ApiResponse.ok("Favicon uploaded", updated));
        } catch (Exception e) {
            return ResponseEntity.badRequest()
                    .body(ApiResponse.<CompanyResponse>error("Favicon upload failed: " + e.getMessage()));
        }
    }

    @PostMapping("/verify-email")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<CompanyResponse>> verifyEmail(Authentication auth) {
        String username = auth != null ? auth.getName() : "system";
        return ResponseEntity.ok(ApiResponse.ok("Email setup verified", companyService.verifyEmail(username)));
    }

    @GetMapping("/microsoft/auth-url")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<String>> microsoftAuthUrl(@RequestParam("state") String state) {
        // state should be generated by UI; backend will echo it back on callback.
        return ResponseEntity.ok(ApiResponse.ok(companyService.getMicrosoftAuthUrl(state)));
    }

    /**
     * OAuth callback — no auth. Microsoft redirects here with code; we exchange it, save tokens, then redirect to frontend success page.
     */
    @GetMapping("/microsoft/callback")
    public ResponseEntity<?> microsoftCallback(
            @RequestParam(value = "code", required = false) String code,
            @RequestParam(value = "error", required = false) String error,
            @RequestParam(value = "error_description", required = false) String errorDescription) {
        // Basic diagnostics to help debug redirect issues.
        log.info("microsoftCallback: codePresent={} error={} errorDescription={}", code != null && !code.isBlank(), error, errorDescription);
        String base = (frontendSuccessUrl != null && !frontendSuccessUrl.isBlank()) ? frontendSuccessUrl.trim() : null;
        if (base == null) {
            log.warn("Microsoft OAuth callback: MS_OAUTH_FRONTEND_SUCCESS_URL is not set; cannot redirect after sign-in");
            String html = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>Configuration Error</title></head><body style=\"font-family:system-ui,sans-serif;max-width:480px;margin:48px auto;padding:24px;text-align:center\">"
                    + "<h2 style=\"color:#c62828\">Server configuration error</h2>"
                    + "<p>Microsoft sign-in cannot complete because <code>MS_OAUTH_FRONTEND_SUCCESS_URL</code> is not set on the server.</p>"
                    + "<p>Contact your administrator to set this environment variable to your frontend success page URL, e.g.:</p>"
                    + "<p><code>http://localhost:4200/auth/microsoft-callback</code> (local dev)</p>"
                    + "<p>You can close this window and try again from Settings after the server is configured.</p></body></html>";
            return ResponseEntity.status(500).contentType(MediaType.TEXT_HTML).body(html);
        }
        URI redirectTo;
        if (code != null && !code.isBlank()) {
            try {
                CompanyResponse company = companyService.connectMicrosoft(code, "system");
                String email = company.getMsAccountEmail() != null ? company.getMsAccountEmail() : "";
                redirectTo = UriComponentsBuilder.fromUriString(base)
                        .queryParam("ms_connected", "1")
                        .queryParam("email", email)
                        .build().toUri();
            } catch (Exception e) {
                redirectTo = UriComponentsBuilder.fromUriString(base)
                        .queryParam("error", "connect_failed")
                        .queryParam("message", e.getMessage() != null ? e.getMessage() : "Connection failed")
                        .build().toUri();
            }
        } else {
            String msg = (errorDescription != null && !errorDescription.isBlank()) ? errorDescription : (error != null ? error : "Unknown error");
            redirectTo = UriComponentsBuilder.fromUriString(base)
                    .queryParam("error", error != null ? error : "unknown")
                    .queryParam("message", msg)
                    .build().toUri();
        }
        return ResponseEntity.status(302).location(redirectTo).build();
    }

    @PostMapping("/microsoft/connect")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<CompanyResponse>> microsoftConnect(@RequestParam("code") String code, Authentication auth) {
        String username = auth != null ? auth.getName() : "system";
        return ResponseEntity.ok(ApiResponse.ok("Microsoft connected", companyService.connectMicrosoft(code, username)));
    }

    @PostMapping("/microsoft/disconnect")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ApiResponse<CompanyResponse>> microsoftDisconnect(Authentication auth) {
        String username = auth != null ? auth.getName() : "system";
        return ResponseEntity.ok(ApiResponse.ok("Microsoft disconnected", companyService.disconnectMicrosoft(username)));
    }
}
